project/zeta/advertising/urls.py
# advertising/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'advertising'
urlpatterns = [
    path('become-a-host/', views.become_a_host, name='become-a-host'),
    path('become-a-host/controller', views.controller, name='controller'),
    # Step 1: Start with the basics
    path('become-a-host/place', views.place, name='1-01'),
    path('become-a-host/bedrooms', views.bedrooms, name='1-02'),
    path('become-a-host/bathrooms', views.bathrooms, name='1-03'),
    path('become-a-host/location', views.location, name='1-04'),
    path('become-a-host/amenities', views.amenities, name='1-05'),
    path('become-a-host/spaces', views.spaces, name='1-06'),
    # Step 2: Set the scene
    path('become-a-host/photos', views.photos, name='2-01'),
    path('become-a-host/description', views.description, name='2-02'),
    path('become-a-host/title', views.title, name='2-03'),
    # Step 3: Get ready for guests
    path('become-a-host/guest-requirements', views.guest_requirements, name='3-01'),
    path('become-a-host/house-rules', views.house_rules, name='3-02'),
    path('become-a-host/review-guest-requirements', views.review_guest_requirements, name='3-03'),
    path('become-a-host/keep-calendar-up-to-date', views.keep_calendar_up_to_date, name='3-04'),
    path('become-a-host/availability-settings', views.availability_settings, name='3-05'),
    path('become-a-host/calendar', views.calendar, name='3-06'),
    path('become-a-host/price', views.price, name='3-07'),
    path('become-a-host/promotion', views.promotion, name='3-08'),
    path('become-a-host/additional-pricing', views.additional_pricing, name='3-09'),
    path('become-a-host/booking-scenarios', views.booking_scenarios, name='3-10'),
    path('become-a-host/local-laws', views.local_laws, name='3-11'),
    
    path('manage-listings/', views.manage_listings, name='manage-listings'),
    path('listing/<int:listing_id>/', views.listing_details, name='listing-details'),
    path('listing/edit/<int:listing_id>/', views.EditListing.as_view(), name='edit-listing'),
    path('listing/delete/<int:listing_id>/', views.delete_listing, name='delete-listing'),
]

project/zeta/request/urls.py
# request/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = 'request'
urlpatterns = [
    path('place-a-request/', views.place_a_request, name='place-a-request'),
    path('place-a-request/controller', views.controller, name='controller'),
    path('place-a-request/place', views.place, name='01'),
    path('place-a-request/bedrooms', views.bedrooms, name='02'),
    path('place-a-request/bathrooms', views.bathrooms, name='03'),
    path('place-a-request/location', views.location, name='04'),
    path('place-a-request/amenities', views.amenities, name='05'),
    path('place-a-request/facilities', views.facilities, name='06'),
    path('place-a-request/description', views.description, name='07'),
    path('place-a-request/further-information', views.further_information, name='08'),
    
    path('manage-requests/', views.manage_requests, name='manage-requests'),
    path('request/<int:request_id>/', views.request_details, name='request-details'),
    path('request/edit/<int:request_id>/', views.EditRequest.as_view(), name='edit-request'),
    path('request/delete/<int:request_id>', views.delete_request, name='delete-request'),
    
    path('manage-bookings/', views.manage_bookings, name='manage-bookings'),
    path('booking/delete/<int:booking_id>', views.delete_booking, name='delete-booking'),
    path('booking/cancel/<int:booking_id>/<int:as_provider>', views.cancel_booking, name='cancel-booking'),
    path('booking/accept/<int:booking_id>', views.accept_booking, name='accept-booking'),
    path('booking/decline/<int:booking_id>', views.decline_booking, name='decline-booking'),
]

project/zeta/search/urls.py
# search/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'search'
urlpatterns = [
    path('search/controller', views.controller, name='controller'),
    path('home', views.index, name='index'),
    path('search/listing', views.listing_results, name='listing-results'),
    path('search/request', views.request_results, name='request-results'),
]

project/zeta/zeta/urls.py
# zeta/urls.py
"""zeta URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls import *
from django.conf.urls.static import static

urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('admin/', admin.site.urls),
    # ex: /users/login/
    path('users/', include('django.contrib.auth.urls')),
    path('', include('users.urls')),
    path('', include('advertising.urls')),
    path('', include('request.urls')),
    path('', include('search.urls')),
    path('', include('review.urls')),
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/zeta/search/models.py
from django.db import models

# Create your models here.

project/zeta/search/views.py
# search/views.py
from django.db.models import Count, F, Q
from django.shortcuts import redirect, render, render_to_response
from django.urls import reverse

from users.models import CustomUser
from advertising.models import Calendar, Listing
from request.models import Booking, Request
from review.models import Review

from collections import defaultdict
from functools import reduce
import calendar
import operator

search_fields = {'city', 'check_in', 'check_out', 'accommodates', 'room_type',
                 'min_price', 'max_price', 'beds', 'bedrooms', 'bathrooms'}
request_fields = {'city', 'check_in', 'check_out', 'accommodates', 'room_type',
                  'min_price', 'max_price', 'beds', 'bedrooms', 'bathrooms'}

# save user search parameters into session
def update_session(request):
    if request.POST['search_type'] == 'listing':
        search_attributes = {}
        for key in request.POST.keys():
            if key in search_fields:
                if key == 'room_type':
                    search_attributes[key] = request.POST.getlist(key)
                else:
                    search_attributes[key] = request.POST[key]
        print(search_attributes)
        if search_attributes:
            request.session['search_attributes'] = search_attributes
    elif request.POST['search_type'] == 'request':
        request_attributes = {}
        for key in request.POST.keys():
            if key in request_fields:
                if key == 'room_type':
                    request_attributes[key] = request.POST.getlist(key)
                else:
                    request_attributes[key] = request.POST[key]
        print(request_attributes)
        if request_attributes:
            request.session['request_attributes'] = request_attributes
    return request

def controller(request):
    next_page = 'search:listing-results'
    if request.method == 'POST':
        # do the specified user operation
        if 'navigation' in request.POST:
            if request.POST['navigation'] == 'clean':
                if request.POST['search_type'] == 'listing' \
                   and 'search_attributes' in request.session:
                    del request.session['search_attributes']
                elif request.POST['search_type'] == 'request' \
                   and 'request_attributes' in request.session:
                    del request.session['request_attributes']
                    next_page = 'search:request-results'
            elif request.POST['navigation'] == 'apply':
                print("APPLYING FILTER")
                request = update_session(request)
                if request.POST['search_type'] == 'request':
                    next_page = 'search:request-results'
    return redirect(reverse(next_page))


def get_listing_filter(request):
    filter_kwargs = {}
    for key in request.session['search_attributes']:
        if key == 'room_type' and request.session['search_attributes'][key]:
            filter_kwargs[key + '__in'] = request.session['search_attributes'][key]
        elif key == 'min_price' and request.session['search_attributes'][key]:
            filter_kwargs['daily_price__gte'] = request.session['search_attributes'][key]
        elif key == 'max_price' and request.session['search_attributes'][key]:
            filter_kwargs['daily_price__lte'] = request.session['search_attributes'][key]
        elif key == 'city' and request.session['search_attributes'][key]:
            filter_kwargs[key + '__icontains'] = request.session['search_attributes'][key]
        elif not (key == 'check_in' or key == 'check_out') \
             and request.session['search_attributes'][key]:
            filter_kwargs[key + '__gte'] = request.session['search_attributes'][key]
    return filter_kwargs

# NOTE:
# The Calendar table stores monthly availability of each listing as string.
# The length of the string is the number of days in that particular month and year,
# in which each character represents the availability of that particular day,
# starting from the left (0:not available, 1:available). 
def get_available_listings(request):
    year, month, day = [int(x) for x in request.session['search_attributes']['check_in'].split('-')]
    check_out = [int(x) for x in request.session['search_attributes']['check_out'].split('-')]
    # create monthly mask(s) based on check in and check out date
    q_objects = Q()
    required_nb_of_months = 1
    while not [year, month] == check_out[:2]:
        days_in_month = calendar.monthrange(year, month)[1]
        curr_month_availability = ''.join(['1' for _ in range(days_in_month-day+1)])
        q_objects |= Q(year=year, month=month, days__regex=r'^.{'+str(day-1)+'}'+curr_month_availability)
        required_nb_of_months += 1
        day = 1
        month += 1
        if month > 12:
            month -= 12
            year += 1
    days_in_month = calendar.monthrange(year, month)[1]
    curr_month_availability = ''.join(['1' for _ in range(check_out[2]-day+1)])
    q_objects |= Q(year=year, month=month, days__regex=r'^.{'+str(day-1)+'}'+curr_month_availability)
    # filter calendar using the monthly mask(s) to find all of the available listings
    calendar_qs = Calendar.objects.filter(q_objects)
    calendar_qs = calendar_qs.values('listing_id').annotate(nb_of_months=Count('listing_id')).filter(nb_of_months=required_nb_of_months)
    listing_ids = calendar_qs.values_list('listing_id', flat=True)
    return listing_ids

def listing_results(request):
    listing_qs = None
    if 'search_attributes' in request.session:
        filter_kwargs = get_listing_filter(request)
        listing_qs = Listing.objects.filter(**filter_kwargs)
        if 'check_in' in request.session['search_attributes'] \
           and request.session['search_attributes']['check_in'] \
           and 'check_out' in request.session['search_attributes'] \
           and request.session['search_attributes']['check_out']:
            listing_ids = get_available_listings(request)
            listing_qs = listing_qs.filter(id__in=listing_ids)
    else:
        listing_qs = Listing.objects.all()
    return render(request, 'search/listing-results.html', {'listings':listing_qs})


def get_request_filter(request):
    filter_kwargs = {}
    for key in request.session['request_attributes']:
        if request.session['request_attributes'][key]:
            if key == 'room_type':
                filter_kwargs[key + '__in'] = request.session['request_attributes'][key]
            elif key == 'min_price':
                filter_kwargs['max_price__gte'] = request.session['request_attributes'][key]
            elif key == 'max_price':
                filter_kwargs['min_price__lte'] = request.session['request_attributes'][key]
            elif key == 'city':
                filter_kwargs[key + '__icontains'] = request.session['request_attributes'][key]
            elif key == 'check_in' or key == 'check_out':
                filter_kwargs[key] = request.session['request_attributes'][key]
            else:
                filter_kwargs[key + '__gte'] = request.session['request_attributes'][key]
    return filter_kwargs

def request_results(request):
    request_qs = None
    if 'request_attributes' in request.session:
        filter_kwargs = get_request_filter(request)
        request_qs = Request.objects.filter(**filter_kwargs)
    else:
        request_qs = Request.objects.all()
    return render(request, 'search/request-results.html', {'requests':request_qs})


def index(request):
    listing_qs = Listing.objects.order_by('id')[:3]
    return render(request, 'search/index.html', {'listings':listing_qs})

project/zeta/templates/search/listing-results.html
<!-- templates/search/result.html -->
{% extends 'base.html' %}

{% block title %}Search Properties{% endblock %}

{% block navigation %}{% include 'navigation.html' %}{% endblock %}

{% block header %}
<div style="margin-top:10%; text-align:center;">
	<b>Search Properties<b>
</div>
{% endblock %}

{% block content %}
<style>
	.title_search{
		margin-top: 20px;
		text-align: center;
	}
	
	.search_out span{
		display: inline-block;
		margin-right: 25px;
		margin-left: 25px;
	}
	
	.search_out{
		text-align: center;
		overflow: hidden;
		position: relative;
	}
	
	.button_part button{
		border-radius: 20px;
		height: 50px;
		width: 100px;
		background-color: #343a40;
		color: #FFFFFF;
		font-size: 20px;
		margin-top: 40px;
		cursor: pointer;

	}
	
	.style-image{
		display: inline-block;
	}
	
	.search_out input {
		border-radius: 5px;
		margin-left: 10px;
	}
</style>

<script>
function ShowElement() {
	var x = document.getElementById("hide").style.display;
	if (x === "none") {
		document.getElementById("hide").style.display = "";
	} else {
		document.getElementById("hide").style.display = "none";
	}
}
</script>

<form action="{% url 'search:controller' %}" method="post" >
	{% csrf_token %}
	
	<input type="hidden" name="search_type" value="listing"/>
	
	<div class="search_out">
		<span>Location: <input type="text" name="city" value='{{ request.session.search_attributes.city }}'></span>
		<span>Check in: <input type="date" name="check_in" value='{{ request.session.search_attributes.check_in }}'></span>
		<span>Check out: <input type="date" name="check_out" value='{{ request.session.search_attributes.check_out }}'></span>
		<span>Guests: <input type="text" name="accommodates" value='{{ request.session.search_attributes.accommodates }}'></span>
	</div>
	
	<div style="text-align: center;">
		<button onclick="ShowElement()" type="button" class="btn btn-success" style=" margin-top:2%; font-size:20px; color: #484848; border-radius: 10px; ">
			Advanced Search
		</button>
	</div>
	
	<div id= "hide" style="display:none;">
		<div class="title_search">
			<h2><b>Room type</b></h2>
		</div>
		<div class="search_out">
			<span >
				<input type="checkbox" name="room_type" value="Entire home/apt" {% if "Entire home/apt" in request.session.search_attributes.room_type %}checked{% endif %}> Entire home/apt
			</span>
			<span>
				<input type="checkbox" name="room_type" value="Private room" {% if "Private room" in request.session.search_attributes.room_type %}checked{% endif %}> Private room
			</span>
			<span>
				<input type="checkbox" name="room_type" value="Shared room" {% if "Shared room" in request.session.search_attributes.room_type %}checked{% endif %}> Shared room
			</span>
		</div>
		
		<div class="title_search" >
			<h2><b>Price</b></h2>
		</div>
		<div class="search_out">
			<span>
				Min: <input type="text" name="min_price" size="15" value='{{ request.session.search_attributes.min_price }}'>
			</span>
			<span>
				Max: <input type="text" name="max_price" size="15" value='{{ request.session.search_attributes.max_price }}'>
			</span>
		</div>
		
		<div class="title_search" >
			<h2><b>Rooms and beds</b></h2>
		</div>
		<div class="search_out">
			<span>
				Beds: <input type="text" name="beds" size="15" value='{{ request.session.search_attributes.beds }}'>
			</span>
			<span>
				Bedrooms: <input type="text" name="bedrooms" size="15" value='{{ request.session.search_attributes.bedrooms }}'>
			</span>
			<span>
				Bathrooms: <input type="text" name="bathrooms" size="15" value='{{ request.session.search_attributes.bathrooms }}'>
			</span>
		</div>
	</div>
	
	<div class="search_out">
		<div class="button_part">
			<button name="navigation" type="submit" value="clean">Clean</button>
			<button name="navigation" type="submit" value="apply">Apply</button>
		</div>
	</div>
</form><br>

<div class="search_out">
	{% for listing in listings %}
		<div class="style-image">
			<a href="{% url 'advertising:listing-details' listing_id=listing.id %}" target="_blank">
				<img src="{{ listing.picture_url }}" alt="Home" style="width:450px;height:300px;">
			</a><br>
			{{ listing.street }}<br>
			<b>{{ listing.title }}</b><br>
			{{ listing.daily_price }} per night<br>
			<br>
		</div>
	{% endfor %}
</div>
{% endblock %}

project/zeta/templates/search/request-results.html
<!-- templates/search/result.html -->
{% extends 'base.html' %}

{% block title %}Search Requests{% endblock %}

{% block navigation %}{% include 'navigation.html' %}{% endblock %}

{% block header %}
<div style="margin-top:10%; text-align:center;">
	<b>Search Requests<b>
</div>
{% endblock %}

{% load static %}

{% block content %}
<style>
	table {
		font-family: arial, sans-serif;
		border-collapse: collapse;
		margin-left: 15%;
		width: 70%;
	}
	
	td, th {
		border: 1px solid #dddddd;
		text-align: left;
		padding: 8px;
	}
	
	.title_search{
		margin-top: 20px;
		text-align: center;
	}
	
	.search_out span{
		display: inline-block;
		margin-right: 25px;
		margin-left: 25px;
	}
	
	.search_out{
		text-align: center;
		overflow: hidden;
		position: relative;
	}
	
	.button_part button{
		border-radius: 20px;
		height: 50px;
		width: 100px;
		background-color: #343a40;
		color: #FFFFFF;
		font-size: 20px;
		margin-top: 40px;
		cursor: pointer;
	}
	
	.style-image{
		display: inline-block;
	}
	
	.search_out input {
		border-radius: 5px;
		margin-left: 10px;
	}
</style>

<script>
function ShowElement() {
	var x = document.getElementById("hide").style.display;
	if (x === "none") {
		document.getElementById("hide").style.display = "";
	} else {
		document.getElementById("hide").style.display = "none";
	}
}
</script>

<form action="{% url 'search:controller' %}" method="post" >
	{% csrf_token %}
	
	<input type="hidden" name="search_type" value="request"/>
	
	<div class="search_out">
		<span>Location: <input type="text" name="city" value='{{ request.session.request_attributes.city }}'></span>
		<span>Check in: <input type="date" name="check_in" value='{{ request.session.request_attributes.check_in }}'></span>
		<span>Check out: <input type="date" name="check_out" value='{{ request.session.request_attributes.check_out }}'></span>
		<span>Guests: <input type="text" name="accommodates" value='{{ request.session.request_attributes.accommodates }}'></span>
	</div>
	
	<div style="text-align: center;">
		<button onclick="ShowElement()" type="button" class="btn btn-success" style=" margin-top:2%; font-size:20px; color: #484848; border-radius: 10px; ">
			Advanced Search
		</button>
	</div>
	
	<div id= "hide" style="display:none;">
		<div class="title_search">
			<h2><b>Room type</b></h2>
		</div>
		<div class="search_out">
			<span >
				<input type="checkbox" name="room_type" value="Entire home/apt" {% if "Entire home/apt" in request.session.request_attributes.room_type %}checked{% endif %}> Entire home/apt
			</span>
			<span>
				<input type="checkbox" name="room_type" value="Private room" {% if "Private room" in request.session.request_attributes.room_type %}checked{% endif %}> Private room
			</span>
			<span>
				<input type="checkbox" name="room_type" value="Shared room" {% if "Shared room" in request.session.request_attributes.room_type %}checked{% endif %}> Shared room
			</span>
		</div>
		
		<div class="title_search" >
			<h2><b>Price</b></h2>
		</div>
		<div class="search_out">
			<span>
				Min: <input type="text" name="min_price" size="15" value='{{ request.session.request_attributes.min_price }}'>
			</span>
			<span>
				Max: <input type="text" name="max_price" size="15" value='{{ request.session.request_attributes.max_price }}'>
			</span>
		</div>
		
		<div class="title_search" >
			<h2><b>Rooms and beds</b></h2>
		</div>
		<div class="search_out">
			<span>
				Beds: <input type="text" name="beds" size="15" value='{{ request.session.request_attributes.beds }}'>
			</span>
			<span>
				Bedrooms: <input type="text" name="bedrooms" size="15" value='{{ request.session.request_attributes.bedrooms }}'>
			</span>
			<span>
				Bathrooms: <input type="text" name="bathrooms" size="15" value='{{ request.session.request_attributes.bathrooms }}'>
			</span>
		</div>
	</div>
	
	<div class="search_out">
		<div class="button_part">
			<button name="navigation" type="submit" value="clean">Clean</button>
			<button name="navigation" type="submit" value="apply">Apply</button>
		</div>
	</div>
</form><br>

<div class="search_out">
	<table>
	{% for request in requests %}
		<tr><td>
			<a class="btn btn-success btn-large" href="{% url 'request:request-details' request_id=request.id %}" style="color:blue" target="_blank">
				{% if request.property_type == 'Apartment' %}
					<img src="{% static 'images/icon_apartment.jpg' %}" alt="Home" style="width:50px;height:50px;">
				{% elif request.property_type == 'Condominium' %}
					<img src="{% static 'images/icon_condominium.jpg' %}" alt="Home" style="width:50px;height:50px;">
				{% elif request.property_type == 'House' %}
					<img src="{% static 'images/icon_house.jpg' %}" alt="Home" style="width:50px;height:50px;">
				{% elif request.property_type == 'Villa' %}
					<img src="{% static 'images/icon_villa.jpg' %}" alt="Home" style="width:50px;height:50px;">
				{% else %}
					<img src="{% static 'images/icon_other.jpg' %}" alt="Home" style="width:50px;height:50px;">
				{% endif %}
				<b>{{ request.title }}</b>
			</a> | 
			{{ request.accommodates }} guest(s) | 
			{{ request.city }} | 
			{{ request.state }} | 
			{{ request.neighbourhood }} | 
			{{ request.check_in }} - {{ request.check_out }} | 
			<b style="color:red">
				$: 
				{% if request.min_price %}
					{% if request.max_price %}
						{{ request.min_price }} - {{ request.max_price }}
					{% else %}
						&ge; {{ request.min_price }}
					{% endif %}
				{% else %}
					{% if request.max_price %}
						&le; {{ request.max_price }}
					{% else %}
						-
					{% endif %}
				{% endif %}
			</b>
			</tr></td>
	{% endfor %}
	</table>
</div>
{% endblock %}