project/zeta/advertising/urls.py
# advertising/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'advertising'
urlpatterns = [
    path('become-a-host/', views.become_a_host, name='become-a-host'),
    path('become-a-host/controller', views.controller, name='controller'),
    # Step 1: Start with the basics
    path('become-a-host/place', views.place, name='1-01'),
    path('become-a-host/bedrooms', views.bedrooms, name='1-02'),
    path('become-a-host/bathrooms', views.bathrooms, name='1-03'),
    path('become-a-host/location', views.location, name='1-04'),
    path('become-a-host/amenities', views.amenities, name='1-05'),
    path('become-a-host/spaces', views.spaces, name='1-06'),
    # Step 2: Set the scene
    path('become-a-host/photos', views.photos, name='2-01'),
    path('become-a-host/description', views.description, name='2-02'),
    path('become-a-host/title', views.title, name='2-03'),
    # Step 3: Get ready for guests
    path('become-a-host/guest-requirements', views.guest_requirements, name='3-01'),
    path('become-a-host/house-rules', views.house_rules, name='3-02'),
    path('become-a-host/review-guest-requirements', views.review_guest_requirements, name='3-03'),
    path('become-a-host/keep-calendar-up-to-date', views.keep_calendar_up_to_date, name='3-04'),
    path('become-a-host/availability-settings', views.availability_settings, name='3-05'),
    path('become-a-host/calendar', views.calendar, name='3-06'),
    path('become-a-host/price', views.price, name='3-07'),
    path('become-a-host/promotion', views.promotion, name='3-08'),
    path('become-a-host/additional-pricing', views.additional_pricing, name='3-09'),
    path('become-a-host/booking-scenarios', views.booking_scenarios, name='3-10'),
    path('become-a-host/local-laws', views.local_laws, name='3-11'),
    
    path('manage-listings/', views.manage_listings, name='manage-listings'),
    path('listing/<int:listing_id>/', views.listing_details, name='listing-details'),
    path('listing/edit/<int:listing_id>/', views.EditListing.as_view(), name='edit-listing'),
    path('listing/delete/<int:listing_id>/', views.delete_listing, name='delete-listing'),
]

project/zeta/request/urls.py
# request/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = 'request'
urlpatterns = [
    path('place-a-request/', views.place_a_request, name='place-a-request'),
    path('place-a-request/controller', views.controller, name='controller'),
    path('place-a-request/place', views.place, name='01'),
    path('place-a-request/bedrooms', views.bedrooms, name='02'),
    path('place-a-request/bathrooms', views.bathrooms, name='03'),
    path('place-a-request/location', views.location, name='04'),
    path('place-a-request/amenities', views.amenities, name='05'),
    path('place-a-request/facilities', views.facilities, name='06'),
    path('place-a-request/description', views.description, name='07'),
    path('place-a-request/further-information', views.further_information, name='08'),
    
    path('manage-requests/', views.manage_requests, name='manage-requests'),
    path('request/<int:request_id>/', views.request_details, name='request-details'),
    path('request/edit/<int:request_id>/', views.EditRequest.as_view(), name='edit-request'),
    path('request/delete/<int:request_id>', views.delete_request, name='delete-request'),
    
    path('manage-bookings/', views.manage_bookings, name='manage-bookings'),
    path('booking/delete/<int:booking_id>', views.delete_booking, name='delete-booking'),
    path('booking/cancel/<int:booking_id>/<int:as_provider>', views.cancel_booking, name='cancel-booking'),
    path('booking/accept/<int:booking_id>', views.accept_booking, name='accept-booking'),
    path('booking/decline/<int:booking_id>', views.decline_booking, name='decline-booking'),
]

project/zeta/users/urls.py
# users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('users/signup/', views.SignUp.as_view(), name='signup'),
    path('users/<int:user_id>/', views.profile, name='profile'),
    path('users/edit/<int:user_id>/', views.EditProfile.as_view(), name='edit'),
]

project/zeta/zeta/urls.py
# zeta/urls.py
"""zeta URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls import *
from django.conf.urls.static import static

urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('admin/', admin.site.urls),
    # ex: /users/login/
    path('users/', include('django.contrib.auth.urls')),
    path('', include('users.urls')),
    path('', include('advertising.urls')),
    path('', include('request.urls')),
    path('', include('search.urls')),
    path('', include('review.urls')),
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/zeta/request/models.py
# request/models.py
from datetime import date, datetime

from django.db import models

from advertising.models import Listing
from users.models import CustomUser

class Request(models.Model):
    visitor       = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

    property_type = models.CharField(max_length=63, default='')
    room_type     = models.CharField(max_length=63, default='')

    accommodates  = models.PositiveSmallIntegerField(default=1)
    bedrooms      = models.PositiveSmallIntegerField(default=1)
    beds          = models.PositiveSmallIntegerField(default=1)
    bed_type      = models.CharField(max_length=31, null=True)

    bathrooms     = models.DecimalField(max_digits=5, decimal_places=2, default=1)

    city          = models.CharField(max_length=63, default='')
    state         = models.CharField(max_length=63, default='')
    neighbourhood = models.CharField(max_length=63, default='')

    amenities     = models.CharField(max_length=2047, null=True)

    access        = models.CharField(max_length=1023, null=True)
    
    title         = models.CharField(max_length=255, default='')
    description   = models.CharField(max_length=1023, null=True)

    check_in      = models.DateField(default=date.today)
    check_out     = models.DateField(default=date.today)
    
    min_price     = models.DecimalField(max_digits=9, decimal_places=2, null=True)
    max_price     = models.DecimalField(max_digits=9, decimal_places=2, null=True)

class Booking(models.Model):
    listing      = models.ForeignKey(Listing, on_delete=models.CASCADE)
    visitor      = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    check_in     = models.DateField()
    check_out    = models.DateField()
    submitted_on = models.DateTimeField(default=datetime.now)
    BOOKING_STATUS_CHOICES = (
        ('P', 'Pending'),
        ('A', 'Accepted'),
        ('D', 'Declined'),
        ('C', 'Canceled'),
    )
    status       = models.CharField(max_length=1, choices=BOOKING_STATUS_CHOICES, default='P')

project/zeta/request/views.py
# request/views.py
from django.contrib import messages
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse
from django.views.generic.edit import UpdateView

from datetime import date
import re

from users.models import CustomUser
from advertising.models import Listing
from request.models import Booking, Request

excluded_keys = {'csrfmiddlewaretoken', 'stage', 'navigation'}
value_to_int  = {'accommodates', 'bedrooms', 'beds', 'bathrooms', 'min_price', 'max_price'}
value_is_list = {'amenities', 'access'}
request_field = {field.name for field in Request._meta.get_fields()} - {'visitor'} | {'visitor_id'}

# save user data for "create a request" into session
def update_session(request):
    print('\nrequest.POST')
    for key in set(request.POST.keys()) - excluded_keys:
        print(key, request.POST[key])
        if request.POST[key]:
            # convert value if necessary
            value = request.POST[key]
            if key in value_to_int:
                value = int(re.findall('\d+', request.POST[key])[0])
            # save session
            request.session[key] = request.POST.getlist(key) if key in value_is_list else value
    print('\nrequest.session')
    for key in request.session.keys():
        print(key, request.session[key])

# get next page for "create a request"
def get_next_page(request):
    stage = int(request.POST['stage'])
    if request.POST['navigation'] == 'back':
        if stage == 1:
            return 'request:place-a-request'
        else:
            stage -= 1
    elif request.POST['navigation'] == 'next':
        if stage == 8:
            return 'request:place-a-request'
        else:
            stage += 1
    return 'request:{0:02d}'.format(stage)

# clean session data for "create a request"
def clean_session(request):
    keys = list(request.session.keys())
    for key in keys:
        if key in request_field:
            del request.session[key]

# save session data for "create a request" into the Request database
def save_session(request):
    # consider user now as visitor and update the database record
    if not request.user.is_visitor:
        user = CustomUser.objects.get(pk=request.session['_auth_user_id'])
        user.is_visitor = True
        user.save()
    request.session['visitor_id'] = request.session['_auth_user_id']
    obj = {key:request.session[key] for key in request.session.keys() if key in request_field}
    Request.objects.create(**obj)

def book_a_listing(request):
    # consider user now as visitor and update the database record
    if not request.user.is_visitor:
        user = CustomUser.objects.get(pk=request.session['_auth_user_id'])
        user.is_visitor = True
        user.save()
    Booking.objects.create(check_in=request.session['search_attributes']['check_in'],
                           check_out=request.session['search_attributes']['check_out'],
                           listing_id=request.POST['listing_id'],
                           visitor_id=request.session['_auth_user_id'],
                           status='P')

def controller(request):
    next_page = 'request:place-a-request'
    kwargs = {}
    if request.method == 'POST':
        # if the request comes with any user data for "create a request"
        if 'stage' in request.POST:
            update_session(request)
            next_page = get_next_page(request)
        # else do the specified user operation
        elif 'navigation' in request.POST:
            if request.POST['navigation'] == 'proceed':
                next_page = 'request:01'
            elif request.POST['navigation'] == 'clean':
                print("CLEANING SESSION")
                clean_session(request)
            elif request.POST['navigation'] == 'save':
                if '_auth_user_id' in request.session:
                    print("SAVING SESSION")
                    save_session(request)
                    clean_session(request)
                    next_page = 'request:manage-requests'
                else:
                    print("PLEASE LOGIN TO CONTINUE")
                    messages.info(request, "PLEASE LOGIN TO CONTINUE")
            elif request.POST['navigation'] == 'book':
                next_page = 'advertising:listing-details'
                kwargs['listing_id'] = request.POST['listing_id']
                if '_auth_user_id' in request.session:
                    if 'search_attributes' in request.session \
                       and 'check_in' in request.session['search_attributes'] \
                       and request.session['search_attributes']['check_in'] \
                       and 'check_out' in request.session['search_attributes'] \
                       and request.session['search_attributes']['check_out']:
                        print("BOOK A LISTING")
                        book_a_listing(request)
                    else:
                        print("PLEASE DETERMINE CHECK IN & CHECK OUT DATE")
                else:
                    print("PLEASE LOGIN TO CONTINUE")
                    messages.info(request, "PLEASE LOGIN TO CONTINUE")
    return redirect(reverse(next_page, kwargs=kwargs))


def place_a_request(request):
    return render(request, 'request/place-a-request.html')

def place(request):
    return render(request, 'request/01-place.html')
def bedrooms(request):
    return render(request, 'request/02-bedrooms.html')
def bathrooms(request):
    return render(request, 'request/03-bathrooms.html')
def location(request):
    return render(request, 'request/04-location.html')
def amenities(request):
    return render(request, 'request/05-amenities.html')
def facilities(request):
    return render(request, 'request/06-facilities.html')
def description(request):
    return render(request, 'request/07-description.html')
def further_information(request):
    return render(request, 'request/08-further-information.html')


def manage_bookings(request):
    context = {}
    if request.user.is_provider:
        print('PROVIDER')
        listing_qs = Listing.objects.filter(provider_id=request.session['_auth_user_id'])
        listing_ids = listing_qs.values_list('id', flat=True)
        context['pending_enquiries']  = Booking.objects.filter(listing_id__in=listing_ids, status='P').order_by('-submitted_on')
        context['accepted_enquiries'] = Booking.objects.filter(listing_id__in=listing_ids, status='A').order_by('-submitted_on')
        context['declined_enquiries'] = Booking.objects.filter(listing_id__in=listing_ids, status='D').order_by('-submitted_on')
        context['canceled_enquiries'] = Booking.objects.filter(listing_id__in=listing_ids, status='C').order_by('-submitted_on')
    if request.user.is_visitor:
        print('VISITOR')
        context['pending_bookings']  = Booking.objects.filter(visitor_id=request.session['_auth_user_id'], status='P').order_by('-submitted_on')
        context['accepted_bookings'] = Booking.objects.filter(visitor_id=request.session['_auth_user_id'], status='A').order_by('-submitted_on')
        context['declined_bookings'] = Booking.objects.filter(visitor_id=request.session['_auth_user_id'], status='D').order_by('-submitted_on')
        context['canceled_bookings'] = Booking.objects.filter(visitor_id=request.session['_auth_user_id'], status='C').order_by('-submitted_on')
    return render(request, 'request/manage-bookings.html', context)

def delete_booking(request, booking_id):
    if '_auth_user_id' in request.session:
        print("DELETE BOOKING")
        booking = Booking.objects.get(pk=booking_id)
        # make sure this operation is done by the booking creator
        if booking.visitor_id == int(request.session['_auth_user_id']):
            booking.delete()
        else:
            print("UNAUTHORIZED ACTION")
    else:
        print("PLEASE LOGIN TO CONTINUE")
    return redirect(reverse('request:manage-bookings'))

def cancel_booking(request, booking_id, as_provider):
    if '_auth_user_id' in request.session:
        print("CANCEL BOOKING")
        booking = Booking.objects.get(pk=booking_id)
        # make sure this operation is done by the booking creator
        # or the corresponding listing provider
        if booking.check_in > date.today() \
           and ((as_provider and booking.listing.provider_id == int(request.session['_auth_user_id']))\
           or (not as_provider and booking.visitor_id == int(request.session['_auth_user_id']))):
            booking.status = 'C'
            booking.save()
        else:
            print("UNAUTHORIZED ACTION")
    else:
        print("PLEASE LOGIN TO CONTINUE")
    return redirect(reverse('request:manage-bookings'))

def accept_booking(request, booking_id):
    if '_auth_user_id' in request.session:
        print("ACCEPT BOOKING")
        booking = Booking.objects.get(pk=booking_id)
        # make sure this operation is done by the corresponding listing provider
        if booking.listing.provider_id == int(request.session['_auth_user_id']):
            booking.status = 'A'
            booking.save()
        else:
            print("UNAUTHORIZED ACTION")
    else:
        print("PLEASE LOGIN TO CONTINUE")
    return redirect(reverse('request:manage-bookings'))

def decline_booking(request, booking_id):
    if '_auth_user_id' in request.session:
        booking = Booking.objects.get(pk=booking_id)
        # make sure this operation is done by the corresponding listing provider
        if booking.listing.provider_id == int(request.session['_auth_user_id']):
            booking.status = 'D'
            booking.save()
        else:
            print("UNAUTHORIZED ACTION")
    else:
        print("PLEASE LOGIN TO CONTINUE")
    return redirect(reverse('request:manage-bookings'))


def manage_requests(request):
    context = {}
    context['requests'] = Request.objects.filter(visitor_id=request.session['_auth_user_id'])
    return render(request, 'request/manage-requests.html', context)

project/zeta/templates/request/edit-request.html
<!-- templates/request/edit-request.html -->
{% extends 'base.html' %}

{% block title %}Edit Request{% endblock %}

{% block navigation %}{% include 'navigation.html' %}{% endblock %}

{% block content %}
<style>
	.colour h1{color: #CECECE;}
		.colour h2{color: #CECECE;}
		.colour h3{color: #CECECE;}
		.colour h4{color: #CECECE;}
		.bg{
			background-image: url('/static/images/bg-01.jpg');
			width:100%;
		}
</style>

<div class="bg">
	<div class="colour">
		<h2>Edit Request</h2>
	</div>
	
	<form method="post">
		{% csrf_token %}
		
		{{ form.as_p }}
		
		<button type="submit" class="btn btn-success btn-large">Update</button>
	</form>
</div>
{% endblock %}

project/zeta/templates/request/manage-bookings.html
<!-- templates/request/manage-bookings.html -->
{% extends 'base.html' %}

{% block title %}Manage Bookings{% endblock %}

{% block navigation %}{% include 'navigation.html' %}{% endblock %}

{% block header %}
<div style="margin-top:10%; text-align:center;">
	<b>Manage Bookings</b>
</div>
{% endblock %}

{% block content %}
<style>
	table {
		font-family: arial, sans-serif;
		border-collapse: collapse;
		width: 100%;
	}
	
	td, th {
		border: 1px solid #dddddd;
		text-align: left;
		padding: 8px;
	}
	
	.whole{
		position: absolute;
		margin-top: 5%;
		left: 10%;
		font-family: "Open Sans", sans-serif;
		font-size: 24px !important;
	}
	
	.button_part button{
		border-radius: 20px;
		height: 50px;
		width: 100px;
		background-color: #343a40;
		color: #FFFFFF;
		font-size: 20px;
		margin-top: 40px;
		cursor: pointer;
	}
	
	.colour span {
		color: #CECECE;
		margin-left: 10px;
		margin-top: 8px;
	}
</style>

<div class = "whole">
	<form action="{% url 'request:controller' %}" method="post">
		{% csrf_token %}
		
		<div class="colour">
			{% if user.is_provider %}
				<h3>Booking Enquiries</h3>
				<table>
					{% for booking in pending_enquiries %}
						<tr><td>
							<a class="btn btn-success btn-large" href="{% url 'users:profile' user_id=booking.visitor_id %}" style="color:green" target="_blank"><b>{{ booking.visitor.first_name }} {{ booking.visitor.last_name }}</b></a> | 
							<a class="btn btn-success btn-large" href="{% url 'advertising:listing-details' listing_id=booking.listing_id %}" style="color:blue" target="_blank"><b>{{ booking.listing.title }}</b></a> | 
							<span>Check in:</span> {{ booking.check_in }} | 
							<span>Check out:</span> {{ booking.check_out }} | 
							<span>Pending</span> | 
							<a class="btn btn-success btn-large" href="{% url 'request:accept-booking' booking_id=booking.id %}" style="color:red"><b>Accept</b></a> | 
							<a class="btn btn-success btn-large" href="{% url 'request:decline-booking' booking_id=booking.id %}" style="color:red"><b>Decline</b></a>
						</tr></td>
					{% endfor %}
				</table><br>
				
				<table>
					{% for booking in accepted_enquiries %}
						<tr><td>
							<a class="btn btn-success btn-large" href="{% url 'users:profile' user_id=booking.visitor_id %}" style="color:green" target="_blank"><b>{{ booking.visitor.first_name }} {{ booking.visitor.last_name }}</b></a> | 
							<a class="btn btn-success btn-large" href="{% url 'advertising:listing-details' listing_id=booking.listing_id %}" style="color:blue" target="_blank"><b>{{ booking.listing.title }}</b></a> | 
							<span>Check in:</span> {{ booking.check_in }} | 
							<span>Check out:</span> {{ booking.check_out }} | 
							<span>Accepted</span> | 
							<a class="btn btn-success btn-large" href="{% url 'request:cancel-booking' booking_id=booking.id as_provider=1 %}" style="color:red"><b>Cancel</b></a>
						</tr></td>
					{% endfor %}
					{% for booking in declined_enquiries %}
						<tr><td>
							<a class="btn btn-success btn-large" href="{% url 'users:profile' user_id=booking.visitor_id %}" style="color:green" target="_blank"><b>{{ booking.visitor.first_name }} {{ booking.visitor.last_name }}</b></a> | 
							<a class="btn btn-success btn-large" href="{% url 'advertising:listing-details' listing_id=booking.listing_id %}" style="color:blue" target="_blank"><b>{{ booking.listing.title }}</b></a> | 
							<span>Check in:</span> {{ booking.check_in }} | 
							<span>Check out:</span> {{ booking.check_out }} | 
							<span>Declined</span>
						</tr></td>
					{% endfor %}
					{% for booking in canceled_enquiries %}
						<tr><td>
							<a class="btn btn-success btn-large" href="{% url 'users:profile' user_id=booking.visitor_id %}" style="color:green" target="_blank"><b>{{ booking.visitor.first_name }} {{ booking.visitor.last_name }}</b></a> | 
							<a class="btn btn-success btn-large" href="{% url 'advertising:listing-details' listing_id=booking.listing_id %}" style="color:blue" target="_blank"><b>{{ booking.listing.title }}</b></a> | 
							<span>Check in:</span> {{ booking.check_in }} | 
							<span>Check out:</span> {{ booking.check_out }} | 
							<span>Canceled</span>
						</tr></td>
					{% endfor %}
				</table>
			{% endif %}
			
			{% if user.is_visitor %}
				<h3>Your Bookings</h3>
				<table>
					{% for booking in pending_bookings %}
						<tr><td>
							<a class="btn btn-success btn-large" href="{% url 'advertising:listing-details' listing_id=booking.listing_id %}" style="color:blue" target="_blank"><b>{{ booking.listing.title }}</b></a> | 
							<span>Check in:</span> {{ booking.check_in }} | 
							<span>Check out</span> {{ booking.check_out }} | 
							<span>Pending</span> | 
							<a class="btn btn-success btn-large" href="{% url 'request:delete-booking' booking_id=booking.id %}" style="color:red"><b>Delete</b></a>
						</tr></td>
					{% endfor %}
				</table><br>
				
				<table>
					{% for booking in accepted_bookings %}
						<tr><td>
							<a class="btn btn-success btn-large" href="{% url 'advertising:listing-details' listing_id=booking.listing_id %}" style="color:blue" target="_blank"><b>{{ booking.listing.title }}</b></a> | 
							<span>Check in:</span> {{ booking.check_in }} | 
							<span>Check out:</span> {{ booking.check_out }} | 
							<span>Accepted</span> | 
							<a  class="btn btn-success btn-large"href="{% url 'request:cancel-booking' booking_id=booking.id as_provider=0 %}" style="color:red"><b>Cancel</b></a>
						</tr></td>
					{% endfor %}
					{% for booking in declined_bookings %}
						<tr><td>
							<a class="btn btn-success btn-large" href="{% url 'advertising:listing-details' listing_id=booking.listing_id %}" style="color:blue" target="_blank"><b>{{ booking.listing.title }}</b></a> | 
							<span>Check in:</span> {{ booking.check_in }} | 
							<span>Check out:</span> {{ booking.check_out }} | 
							<span>Declined</span>
						</tr></td>
					{% endfor %}
					{% for booking in canceled_bookings %}
						<tr><td>
							<a class="btn btn-success btn-large" href="{% url 'advertising:listing-details' listing_id=booking.listing_id %}" style="color:blue" target="_blank"><b>{{ booking.listing.title }}</b></a> | 
							<span>Check in:</span> {{ booking.check_in }} | 
							<span>Check out:</span> {{ booking.check_out }} | 
							<span>Canceled</span>
						</tr></td>
					{% endfor %}
				</table>
			{% endif %}
		</div>
	</form>
</div>
{% endblock %}

project/zeta/templates/request/manage-requests.html
<!-- templates/advertising/manage-requests.html -->
{% extends 'base.html' %}

{% block title %}Manage Requests{% endblock %}

{% block navigation %}{% include 'navigation.html' %}{% endblock %}

{% block header %}
<div style="margin-top:10%; text-align:center;">
	<b>Manage Requests</b>
</div>
{% endblock %}

{% block content %}
<style>
	table {
		font-family: arial, sans-serif;
		border-collapse: collapse;
		width: 100%;
	}
	
	.colour h1{color: #CECECE;}
	
	.colour h2{color: #CECECE;}
	
	.colour h3{color: #CECECE;}
	
	.colour h4{color: #CECECE;}
	
	.bg{
		background-image: url('/static/images/bg-01.jpg');
		width:100%;
	}
	
	td, th {
		border: 1px solid #dddddd;
		text-align: left;
		padding: 8px;
	}
	
	.whole{
		position: absolute;
		margin-top: 5%;
		left: 10%;
		font-family: "Open Sans", sans-serif;
		font-size: 24px !important;
	}
	
	.button_part button{
		border-radius: 20px;
		height: 50px;
		width: 100px;
		background-color: #343a40;
		color: #FFFFFF;
		font-size: 20px;
		margin-top: 40px;
		cursor: pointer;
	}
</style>

<div class = "whole">
	<form action="{% url 'request:controller' %}" method="post">
		{% csrf_token %}
		
		<table>
		{% for request in requests %}
			<tr><td>
			<a class="btn btn-success btn-large" href="{% url 'request:request-details' request_id=request.id %}" style="color:blue" target="_blank"><b>{{ request.title }}</b></a> | 
			{{ request.check_in }} | 
			{{ request.check_out }} | 
			<a class="btn btn-success btn-large" href="{% url 'request:delete-request' request_id=request.id %}" style="color:red" class="btn btn-success btn-large"><b>Delete</b></a> | 
			<a class="btn btn-success btn-large" href="{% url 'request:edit-request' request_id=request.id %}" style="color:red" target="_blank" class="btn btn-success btn-large"><b>Edit</b></a>
			</tr></td>
		{% endfor %}
		</table>
	</form>
</div>
{% endblock %}

project/zeta/templates/request/request-details.html
<!-- templates/search/request-details.html -->
{% extends 'base.html' %}

{% block title %}{{ request.title }}{% endblock %}

{% block navigation %}{% include 'navigation.html' %}{% endblock %}

{% block header %}
<div style="margin-top:10%; text-align:center;">
	<b>{{ request.title }}</b>
</div>
{% endblock %}

{% block content %}
<style>
	.main-wrap {
		overflow: hidden;
	}
	
	.left-body {
		float: left;
		width: 50%;
	}
	
	.right-body {
		float: right;
		width: 50%;
	}
	.colour span {
			color: #CECECE;
			margin-left: 10px;
			margin-top: 8px;
		}
</style>

<form action="{% url 'request:controller' %}" method="post">
	{% csrf_token %}
	
	<input type="hidden" name="request_id" value="{{ request.id }}"/>
	
	<div class="main-wrap">
		<div class="left-body">
			{{ request.neighbourhood }}<br>
			{{ request.city }}<br>
			{{ request.state }}<br>
			{{ request.property_type }}<br>
			{{ request.room_type }}<br>
			{{ request.accommodates }} guest(s)<br>
			{{ request.bedrooms }} bedroom(s)<br>
			{{ request.beds }} bed(s)<br>
			{{ request.bed_type }}<br>
			{{ request.bathrooms }} bath(s)<br>
			{{ request.check_in }} - {{ request.check_out }}<br>
			{{ request.min_price }} - {{ request.max_price }}<br>
			{% if request.visitor_id == user.id %}
				<a href="{% url 'request:edit-request' request_id=request.id %}" style="color:red">Edit</a>
			{% else %}
				<a href="" style="color:red">Make an Offer</a>
			{% endif %}
		</div>
		
		<div class="right-body">
			<span>Description:</span><br>
			{{ request.description }}<br>
			<br>
			
			<span>Amenities:</span><br>
			{{ request.amenities }}<br>
			<br>
			
			<span>Access:</span><br>
			{{ request.access }}
		</div>
	</div>
</form>
{% endblock %}