project/zeta/advertising/urls.py
# advertising/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'advertising'
urlpatterns = [
    path('become-a-host/', views.become_a_host, name='become-a-host'),
    path('become-a-host/controller', views.controller, name='controller'),
    # Step 1: Start with the basics
    path('become-a-host/place', views.place, name='1-01'),
    path('become-a-host/bedrooms', views.bedrooms, name='1-02'),
    path('become-a-host/bathrooms', views.bathrooms, name='1-03'),
    path('become-a-host/location', views.location, name='1-04'),
    path('become-a-host/amenities', views.amenities, name='1-05'),
    path('become-a-host/spaces', views.spaces, name='1-06'),
    # Step 2: Set the scene
    path('become-a-host/photos', views.photos, name='2-01'),
    path('become-a-host/description', views.description, name='2-02'),
    path('become-a-host/title', views.title, name='2-03'),
    # Step 3: Get ready for guests
    path('become-a-host/guest-requirements', views.guest_requirements, name='3-01'),
    path('become-a-host/house-rules', views.house_rules, name='3-02'),
    path('become-a-host/review-guest-requirements', views.review_guest_requirements, name='3-03'),
    path('become-a-host/keep-calendar-up-to-date', views.keep_calendar_up_to_date, name='3-04'),
    path('become-a-host/availability-settings', views.availability_settings, name='3-05'),
    path('become-a-host/calendar', views.calendar, name='3-06'),
    path('become-a-host/price', views.price, name='3-07'),
    path('become-a-host/promotion', views.promotion, name='3-08'),
    path('become-a-host/additional-pricing', views.additional_pricing, name='3-09'),
    path('become-a-host/booking-scenarios', views.booking_scenarios, name='3-10'),
    path('become-a-host/local-laws', views.local_laws, name='3-11'),
    
    path('manage-listings/', views.manage_listings, name='manage-listings'),
    path('listing/<int:listing_id>/', views.listing_details, name='listing-details'),
    path('listing/edit/<int:listing_id>/', views.EditListing.as_view(), name='edit-listing'),
    path('listing/delete/<int:listing_id>/', views.delete_listing, name='delete-listing'),
]

project/zeta/request/urls.py
# request/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = 'request'
urlpatterns = [
    path('place-a-request/', views.place_a_request, name='place-a-request'),
    path('place-a-request/controller', views.controller, name='controller'),
    path('place-a-request/place', views.place, name='01'),
    path('place-a-request/bedrooms', views.bedrooms, name='02'),
    path('place-a-request/bathrooms', views.bathrooms, name='03'),
    path('place-a-request/location', views.location, name='04'),
    path('place-a-request/amenities', views.amenities, name='05'),
    path('place-a-request/facilities', views.facilities, name='06'),
    path('place-a-request/description', views.description, name='07'),
    path('place-a-request/further-information', views.further_information, name='08'),
    
    path('manage-requests/', views.manage_requests, name='manage-requests'),
    path('request/<int:request_id>/', views.request_details, name='request-details'),
    path('request/edit/<int:request_id>/', views.EditRequest.as_view(), name='edit-request'),
    path('request/delete/<int:request_id>', views.delete_request, name='delete-request'),
    
    path('manage-bookings/', views.manage_bookings, name='manage-bookings'),
    path('booking/delete/<int:booking_id>', views.delete_booking, name='delete-booking'),
    path('booking/cancel/<int:booking_id>/<int:as_provider>', views.cancel_booking, name='cancel-booking'),
    path('booking/accept/<int:booking_id>', views.accept_booking, name='accept-booking'),
    path('booking/decline/<int:booking_id>', views.decline_booking, name='decline-booking'),
]

project/zeta/search/urls.py
# search/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'search'
urlpatterns = [
    path('search/controller', views.controller, name='controller'),
    path('home', views.index, name='index'),
    path('search/listing', views.listing_results, name='listing-results'),
    path('search/request', views.request_results, name='request-results'),
]

project/zeta/users/urls.py
# users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('users/signup/', views.SignUp.as_view(), name='signup'),
    path('users/<int:user_id>/', views.profile, name='profile'),
    path('users/edit/<int:user_id>/', views.EditProfile.as_view(), name='edit'),
]

project/zeta/zeta/urls.py
# zeta/urls.py
"""zeta URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls import *
from django.conf.urls.static import static

urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('admin/', admin.site.urls),
    # ex: /users/login/
    path('users/', include('django.contrib.auth.urls')),
    path('', include('users.urls')),
    path('', include('advertising.urls')),
    path('', include('request.urls')),
    path('', include('search.urls')),
    path('', include('review.urls')),
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/zeta/templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	
	{% load static %}
	
	<link href="https://fonts.googleapis.com/css?family=Rubik:300,400,500" rel="stylesheet"/>
	<link rel="stylesheet" href="http://www.cse.unsw.edu.au/~z5123906/animate.css" type='text/css'/>
	<link rel="stylesheet" href="http://www.cse.unsw.edu.au/~z5123906/aos.css" type='text/css'/>
	<link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css' %}" type='text/css'/>
	<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type='text/css'/>
	<link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}" type='text/css'/>
	<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}" type='text/css'/>
	<link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}" type='text/css'/>
	<link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}" type='text/css'/>
	<link rel="stylesheet" href="{% static 'css/jquery.timepicker.css' %}" type='text/css'/>
	<link rel="stylesheet" href="{% static 'css/flaticon.css'%}"  type='text/css'/>
	<link rel="stylesheet" href="{% static 'css/icomoon.css'%}"  type='text/css'/>
	<link rel="stylesheet" href="{% static 'css/style.css'%}" type='text/css'/>
	
	<script src="{% static 'js/jquery.min.js' %}" />
	<script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
	<script src="{% static 'js/popper.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
	<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
	<script src="{% static 'js/jquery.stellar.min.js' %}"></script>
	<script src="{% static 'js/owl.carousel.min.js' %}"></script>
	<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
	<script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
	<script src="{% static 'js/aos.js' %}"></script>
	<script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
	<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
	<script src="{% static 'js/google-map.js' %}"></script>
	<script src="{% static 'js/main.js'%}"></script>
	
	<title>{% block title %}{% endblock %}</title>
</head>

<body>
	{% block navigation %}
	{% load bootstrap4 %}
	<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
	<div class="container">
		<a class="navbar-brand" href="{% url 'search:listing-results' %}">&#918;&#917;&#915;&#913;</a>
	</div>
	</nav>
	{% endblock %}
	<h1>{% block header %}{% endblock %}</h1>
	<main>
		{% block content %}{% endblock %}
	</main>
</body>
</html>

project/zeta/templates/home.html
<!-- templates/home.html -->
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block navigation %}{% endblock %}

{% block content %}
{% if user.is_authenticated %}
	Hi {{ user.email }}!
	<p><a href="{% url 'logout' %}">logout</a></p>
{% else %}
{% load static %}
<!-- <img src="{% static "my_app/example.jpg" %}" alt="My image"> -->


<div class="limiter">
  <div class="container-login100"  alt="backimage">
    <div class="wrap-login100" style="padding: 30px 0px 50px 0px;">
      <span class="login100-form-title" style="padding-bottom: 41px;">
        Zeta Accommodation
      </span>

      <form class="login100-form validate-form " style="padding: 5px 0px 33px 0px;"  method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit">Login</button>
        </form>
      <div id="dropDownSelect1"></div>
        <p>You are not logged in</p>
        <a href="{% url 'login' %}">login</a>
        <a href="{% url 'users:signup' %}">signup</a>


      <form class="login100-form validate-form " style="padding: 5px 0px 33px 0px;" method="post">
        <div class="wrap-input100 validate-input" data-validate = "Enter username">
          <input class="input100" type="text" name="username" placeholder="User name">
          <span class="focus-input100"></span>
          {% csrf_token %}
        </div>

        <div class="wrap-input100 validate-input" data-validate="Enter password">
          <input class="input100" type="password" name="pass" placeholder="Password">
          <span class="focus-input100"></span>
          {{ form.as_p }}
        </div>
      
        
        
        <div class="container-login100-form-btn" style="margin-top: 32px;">
          <button class="login100-form-btn"  type="submit" >
              <a href="{% url 'login' %}" style="font-family: Ubuntu-Bold;
              font-size: 18px;
              color: #fff;">login</a>
          </button>
        </div>

        <div class="container-login100-form-btn" style="margin-top: 32px;">
          <button class="login100-form-btn"  type="submit">
            <a href="{% url 'users:signup' %}" style="font-family: Ubuntu-Bold;
            font-size: 18px;
            color: #fff;">signup</a>
          </button>
        </div>

      </form>
    </div>
  </div>
</div>

<!-- <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
<div id="dropDownSelect1"></div>
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">login</a>
  <a href="{% url 'users:signup' %}">signup</a> -->
{% endif %}
{% endblock %}

project/zeta/templates/navigation.html
{% load bootstrap4 %}


<style>
	.dropbtn {
		background-color: #343a40;
		color: white;
		font-size: 16px;
		border: none;
		cursor: pointer;
	}
	
	.dropbtn:hover, .dropbtn:focus {
		background-color: #343a40;
	}
	
	.dropdown {
		position: relative;
		display: inline-block;
	}
	
	.dropdown-content {
		display: none;
		position: absolute;
		background-color: #f1f1f1;
		min-width: 160px;
		overflow: auto;
		box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
		z-index: 1;
	}
	
	.dropdown-content a {
		color: black;
		padding: 12px 16px;
		text-decoration: none;
		display: block;
	}
	
	.dropdown a:hover {background-color: #ddd;}
	
	.show {display: block;}
	
	.buttonsearch {
		margin-bottom: 5px;
	}
</style>

<script>
/* When the user clicks on the button, 
toggle between hiding and showing the dropdown content */
function myFunction() {
    document.getElementById("myDropdown").classList.toggle("show");
}
function myFunction2() {
    document.getElementById("myDropdown2").classList.toggle("show");
}

// Close the dropdown if the user clicks outside of it
window.onclick = function(event) {
  if (!event.target.matches('.dropbtn')) {

    var dropdowns = document.getElementsByClassName("dropdown-content");
    var i;
    for (i = 0; i < dropdowns.length; i++) {
      var openDropdown = dropdowns[i];
      if (openDropdown.classList.contains('show')) {
        openDropdown.classList.remove('show');
      }
    }
  }
}
</script>

<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar" style="background-color:#343a40 !important;">
	<div class="container">
		<a class="navbar-brand" href="{% url 'search:index' %}">ZETA</a>


			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
				<span class="oi oi-menu"></span> Menu
			</button>
		
		<div class="collapse navbar-collapse" id="ftco-nav">
			<ul class="navbar-nav ml-auto">
				<li class="nav-item active">
					<form action="{% url 'search:controller' %}" method="post" >
						{% csrf_token %}
						<input type="hidden" name="search_type" value="listing"/>
						<div style=" border-radius:30px; margin-top:30px;">
							<button  style= "background-color:#343a40 !important; color:#CECECE;" name="navigation" type="submit" value="apply">

								Search
							</button>
							<input type="text" name="city" value='{{ request.session.search_attributes.city }}'>
						</div>
					</form>
				</li>
				
				<li class="nav-item active"><a href="{% url 'search:index' %}" class="nav-link">Home</a></li>
				
				{% if user.is_authenticated %}
					<li class="nav-item"><a href="{% url 'users:profile' user_id=user.id %}" class="nav-link">Profile</a></li>
					
					<div style="margin-top:30px;">
						<div class="dropdown">
							<button onclick="myFunction2()" class="dropbtn">Manage</button>
							<div id="myDropdown2" class="dropdown-content">
								<a href="{% url 'request:manage-bookings' %}">Bookings</a>
								{% if user.is_provider %}
								<a href="{% url 'advertising:manage-listings' %}">Listings</a>
								{% endif %}
								{% if user.is_visitor %}
								<a href="{% url 'request:manage-requests' %}">Requests</a>
								{% endif %}
							</div>
						</div>
					</div>
				{% endif %}
				
				<li class="nav-item"><a href="{% url 'request:place-a-request' %}" class="nav-link">Place a request</a></li>
				
				<div style="margin-top:30px;">
					<div class="dropdown">
						<button onclick="myFunction()" class="dropbtn">Become a Host</button>
						<div id="myDropdown" class="dropdown-content">
							<a href="{% url 'advertising:become-a-host' %}">Host a home</a>
							<a href="{% url 'search:request-results' %}">Search visitor request</a>
						</div>
					</div>
				</div>
				
				{% if user.is_authenticated %}
					<li class="nav-item"><a href="{% url 'logout' %}" class="nav-link">Log out</a></li>
				{% else %}
					<li class="nav-item"><a href="{% url 'users:signup' %}" class="nav-link">Sign up</a></li>
					<li class="nav-item"><a href="{% url 'login' %}" class="nav-link">Log in</a></li>
				{% endif %}
			</ul>
		</div>
	</div>
</nav>