project/zeta/review/urls.py
# request/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = 'review'
urlpatterns = [
    path('review/add', views.add_visitor_review, name='add-visitor-review'),
    path('review/delete/<int:review_id>/', views.delete_visitor_review, name='delete-visitor-review'),
    path('review/edit/<int:review_id>/', views.EditReview.as_view(), name='edit-visitor-review'),
]

project/zeta/users/urls.py
# users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('users/signup/', views.SignUp.as_view(), name='signup'),
    path('users/<int:user_id>/', views.profile, name='profile'),
    path('users/edit/<int:user_id>/', views.EditProfile.as_view(), name='edit'),
]

project/zeta/zeta/urls.py
# zeta/urls.py
"""zeta URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls import *
from django.conf.urls.static import static

urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('admin/', admin.site.urls),
    # ex: /users/login/
    path('users/', include('django.contrib.auth.urls')),
    path('', include('users.urls')),
    path('', include('advertising.urls')),
    path('', include('request.urls')),
    path('', include('search.urls')),
    path('', include('review.urls')),
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/zeta/review/models.py
# review/models.py
from datetime import date

from django.db import models

from advertising.models import Listing
from users.models import CustomUser

class Review(models.Model):
    REVIEW_TYPE_CHOICES = (
        (0, 'Visitor review Listing'),
        (1, 'Provider review Visitor'),
    )
    review_type  = models.PositiveSmallIntegerField(choices=REVIEW_TYPE_CHOICES)
    provider     = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='provider_id')
    visitor      = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='visitor_id')
    listing      = models.ForeignKey(Listing, on_delete=models.CASCADE)
    rating       = models.DecimalField(max_digits=5, decimal_places=2)
    content      = models.CharField(max_length=4095)
    submitted_on = models.DateField(default=date.today)

project/zeta/review/views.py
# review/views.py
from django.http import Http404
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse
from django.views.generic.edit import UpdateView

from datetime import date

from advertising.models import Listing
from request.models import Booking
from review.models import Review

def user_has_finished_their_stay(listing_id, visitor_id):
    booking_qs = Booking.objects.filter(listing_id=listing_id,
                                        visitor_id=visitor_id,
                                        check_out__lt=date.today(),
                                        status='A')
    return True if booking_qs else False

def add_visitor_review(request):
    if request.method == 'POST':
        if request.user.is_authenticated and request.user.is_visitor:
            if user_has_finished_their_stay(request.POST['listing_id'], request.user.id):
                print("ADD VISITOR REVIEW")
                listing = Listing.objects.get(pk=request.POST['listing_id'])
                Review.objects.create(review_type=0,
                                      rating=0,
                                      content=request.POST['content'],
                                      listing_id=request.POST['listing_id'],
                                      provider_id=listing.provider_id,
                                      visitor_id=request.user.id)
            else:
                print("UNAUTHORIZED ACTION")
        else:
            print("PLEASE LOGIN TO CONTINUE")
        return redirect(reverse('advertising:listing-details',
                                kwargs={'listing_id':request.POST['listing_id']}))
    else:
        raise Http404("UNAUTHORIZED ACTION")

def delete_visitor_review(request, review_id):
    listing_id = None
    if request.user.is_authenticated and request.user.is_visitor:
        review = Review.objects.get(pk=review_id)
        listing_id = review.listing_id
        if user_has_finished_their_stay(review.listing_id, review.visitor_id):
            print("DELETE VISITOR REVIEW")
            # make sure this operation is done by the review creator
            if review.visitor_id == int(request.session['_auth_user_id']):
                review.delete()
            else:
                print("UNAUTHORIZED ACTION")
        else:
            print("UNAUTHORIZED ACTION")
    else:
        print("PLEASE LOGIN TO CONTINUE")
    if listing_id:
        return redirect(reverse('advertising:listing-details',
                                kwargs={'listing_id':listing_id}))
    else:
        raise Http404("UNAUTHORIZED ACTION")

class EditReview(UpdateView):
    model = Review
    fields = ['rating', 'content']
    template_name = 'review/edit-review.html'

    def get_form(self, form_class=None):
        form = super(EditReview, self).get_form(form_class)
        for field in form.fields:
            form.fields[field].required = False
        return form

    def get_object(self):
        review_id = None
        if self.request.user.is_authenticated:
            review = Review.objects.get(pk=self.kwargs['review_id'])
            if review.visitor_id == self.request.user.id:
                review_id = self.kwargs['review_id']
                self.listing_id = review.listing_id
        return get_object_or_404(Review, pk=review_id)

    def get_success_url(self):
        return reverse('advertising:listing-details',
                       kwargs={'listing_id':self.listing_id})

project/zeta/templates/review/edit-review.html
<!-- templates/review/edit-review.html -->
{% extends 'base.html' %}

{% block title %}Edit Review{% endblock %}

{% block navigation %}{% include 'navigation.html' %}{% endblock %}

{% block content %}
<style>
	.whole{
		top: 5%; 
		left: 5%; 
		font-family: "Open Sans", sans-serif;
		font-size: 20px !important;
		color: #CECECE;
		margin-top:10%;
		display: inline-block;
		padding-left:100px;
		padding-top:5px;
		padding-bottom:400px;
	}
	.colour h1{color: #CECECE;}
	.colour h2{color: #CECECE;}
	.colour h3{color: #CECECE;}
	.colour h4{color: #CECECE;}
	.bg{
		background-image: url('/static/images/bg-01.jpg');
		width:100%;
	}
</style>

<div class="bg">
	<div class= "whole">
		<div class="colour">
			<h2>Edit Review</h2>
		</div>
		
		<form method="post">
			{% csrf_token %}
			
			{{ form.as_p }}
			
			<button type="submit" class="btn btn-success btn-large">Update</button>
		</form>
	</div>
</div>
{% endblock %}

project/zeta/templates/review/visitor_review.html
<!-- templates/review/visitor_review.html -->
<h2>Reviews</h2>
<h5 style="color:orange"><b>Rating: {{ rating|default:'-' }}</b></h5>

<form action="{% url 'review:add-visitor-review' %}" method="post">
	{% csrf_token %}
	
	<input type="hidden" name="listing_id" value="{{ listing.id }}">
	
	<b>Score:</b> <input type="number" name="score" min="0" max="100"/><br>
	<textarea name="content" placeholder="enter text" cols="50" rows="3"></textarea><br>
	
	<button type="submit">post</button>
</form><br>

{% for review in reviews %}
	<a href="{% url 'users:profile' user_id=review.visitor_id %}"><b>{{ review.visitor.first_name }}</b></a><br>
	{{ review.content }}
	{% if review.visitor_id == user.id %}<br>
	<a href="{% url 'review:edit-visitor-review' review_id=review.id %}" style="color:red"><b>Edit</b></a> | 
	<a href="{% url 'review:delete-visitor-review' review_id=review.id %}" style="color:red"><b>Delete</b></a>
	{% endif %}
	<br><br>
{% endfor %}